name: Screenshot page
on:
  push:
    branches:
      - setup-screenshots
permissions:
  contents: write
jobs:
  screenshot:
    strategy:
      matrix:
        os: [
        ubuntu-latest,
        #macos-latest,
        #windows-latest
        ]
        width: [1200, 992, 768, 600]
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: screenshots
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S')"
      - name: Declare branch variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Take screenshots
        id: get_screenshots
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://bnichs.github.io/
          destination: screenshot-${{ matrix.os }}-${{ matrix.width }}-${{ steps.date.outputs.date }}-${{ steps.vars.outputs.sha_short }}.png
          width: ${{ matrix.width }}
      - name: Commit report
        run: |
          export branch="branch-${{ steps.vars.output.branch }}"
          mkdir -p $branch
          echo ${{ steps.get_screenshots.outputs.path }}
          cp ${{ steps.get_screenshots.outputs.path }} ./$branch
          ls
          git branch --list
          git config --global user.name 'Ben Nichols (auto)'
          git config --global user.email 'mail@ben-nichols.net'
          git add .
          git commit -am "Automated screenshots report"
          git push