name: Screenshot page
on:
  push:
    branches:
      - setup-screenshots
permissions:
  contents: write
jobs:
  screenshot:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: screenshots
      - name: get_screenshots
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://bnichs.github.io/
          destination: screenshot-${{ matrix.os }}.png
      - name: Commit report
        run: |
          echo ${{ steps.get_screenshots.output }}
          ls
          git branch --list
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git checkout screenshots
          git add "screenshot*"
          git commit -am "Automated screenshots report"
          git push